apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-app
  labels:
    app: ci-cd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-cd-app
  template:
    metadata:
      labels:
        app: ci-cd-app
    spec:
      containers:
        - name: ci-cd-app
          # Tag will be set by the deployment job using `kubectl set image`
          image: DOCKER_USERNAME/ci-cd-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ci-cd-service
  labels:
    app: ci-cd-app
spec:
  type: NodePort
  selector:
    app: ci-cd-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
